# =============================================================================
# Konfigurasi Utama
# =============================================================================

# Bahasa situs Anda (misal: "en", "id", "zh-Hans", "zh-Hant")
lang: id

# Zona waktu Anda (misal: "America/New_York", "Asia/Jakarta", "Asia/Makassar")
timezone: Asia/Makassar

# =============================================================================
# Informasi Situs & Author (Sidebar Kiri)
# =============================================================================

# Judul situs, akan tampil besar di atas
title: Rezky Robbyyanto Akbari

# Tagline, tampil di bawah judul
tagline: Menjembatani Teknologi dan Strategi Bisnis Melalui Sistem Informasi.

# Deskripsi singkat situs Anda untuk SEO
description: Robby Work

# URL: Ini adalah URL utama USERNAME Anda
url: https://RezkyRobby23h.github.io

# BASEURL: Ini adalah NAMA REPOSITORI Anda (ini akan memperbaiki halaman kosong)
baseurl: /rezkyrobbyyanto.github.io

# Informasi Author (untuk postingan blog)
author: Rezky Robbyyanto Akbari

# Avatar (Foto Profil)
# PENTING: Unggah foto Anda ke folder /assets/img/ dan beri nama avatar.jpg
avatar: /assets/img/avatar.jpg

# Email Anda
email: reskybobby04@gmail.com

# Tautan Media Sosial
social:
  name: Rezky Robbyyanto Akbari
  email: reskybobby04@gmail.com
  links:
    - name: GitHub
      url: https://github.com/RezkyRobby23h
    # - name: LinkedIn
    #   url: https://www.linkedin.com/in/username-anda
    # - name: Twitter
    #   url: https://twitter.com/username_anda
    # - name: Instagram
    #   url: https://www.instagram.com/username_anda

# =============================================================================
# Pengaturan Tampilan & Teknis
# =============================================================================

# Mode Tampilan (Pilihan: "light", "dark", "dual")
theme_mode: dual

# Informasi GitHub (untuk link di footer, dll)
github:
  username: RezkyRobby23h

# Pengaturan Komentar (opsional)
# disqus:
#   shortname: # Ganti dengan shortname Disqus Anda

# =============================================================================
# Pengaturan Build Jekyll (Umumnya tidak perlu diubah)
# =============================================================================

# Markdown processor
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Ruby Sass
sass:
  style: compressed

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Paginate (Jumlah post per halaman di Halaman Utama)
paginate: 10
paginate_path: /page:num/

# Exclude files (File yang diabaikan oleh Jekyll)
exclude:
  - .github/
  - .jekyll-cache/
  - .bundle/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - docs/

# Google Analytics (opsional)
# analytics:
#   google:
#     id: # Ganti dengan ID Google Analytics Anda (misal: G-XXXXXXXXXX)